[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
arena_vault = "fnZeSU5WzuCq32fLJLRVEkcQvB5TNAH8vMskh9ZKwgW"

[programs.devnet]
arena_vault = "fnZeSU5WzuCq32fLJLRVEkcQvB5TNAH8vMskh9ZKwgW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet.json"

[scripts]
test = "node tests/vault.test.mjs"
